import { Ionicons } from "@expo/vector-icons";
import { router, Stack, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { API_BASE } from "../utils/appconfig";
type Squad="East"|"West"; type Player={id:string;name:string;jerseyNumber:string;position:string;teamName:string;squad:Squad;batting?:boolean;battingOrder?:number|null}; type GameState={currentBatterIndex:number};
export default function AnnouncerLineupScreen(){
 const p=useLocalSearchParams<{gameId?:string;divisionId?:string;gameTitle?:string;eastDugout?:string;westDugout?:string;accentColor?:string;squad?:string}>(); const squad:Squad=String(p.squad)==="West"?"West":"East"; const [batting,setBatting]=useState<Player[]>([]);const[subs,setSubs]=useState<Player[]>([]);const[manager,setManager]=useState("");const[currentIndex,setCurrentIndex]=useState(0);const[loading,setLoading]=useState(true);const[lastUpdated,setLastUpdated]=useState("Loading...");
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t);},[p.divisionId,squad]);
 async function load(){try{const[r1,r2]=await Promise.all([fetch(`${API_BASE}/api/lineups/${p.divisionId}/${squad}`),fetch(`${API_BASE}/api/game-state/${p.divisionId}/${squad}`)]);const[j,s]=await Promise.all([r1.json(),r2.json()]);const players:Player[]=j?.ok&&j.lineup?.players?j.lineup.players:[];setBatting(players.filter(x=>x.batting).sort((a,b)=>(a.battingOrder||999)-(b.battingOrder||999)));setSubs(players.filter(x=>!x.batting));setManager(j?.managerName||j?.lineup?.managerName||j?.manager?.displayName||j?.manager?.name||j?.assignment?.managerName||j?.assignment?.displayName||"");setCurrentIndex(Number(s?.gameState?.currentBatterIndex||0));setLastUpdated("Updated Just Now");}catch(e){console.log("PUBLIC LINEUP LOAD ERROR",e);}finally{setLoading(false);}}
 function back(){router.replace({pathname:"/announcer",params:{gameId:p.gameId||"",divisionId:p.divisionId||"",gameTitle:p.gameTitle||"",eastDugout:p.eastDugout||"",westDugout:p.westDugout||"",accentColor:p.accentColor||""}});}
 function row(player:Player,index?:number){const current=index!==undefined&&index===currentIndex;return <View key={`${player.id}-${index??"s"}`} style={[styles.row,current&&styles.currentRow]}>{index!==undefined?<Text style={styles.order}>{index+1}</Text>:null}<Text style={[styles.jersey,squad==="East"?styles.east:styles.west]}>#{player.jerseyNumber||"--"}</Text><View style={styles.info}><Text style={styles.name}>{player.name}</Text><Text style={styles.meta}>{player.position||"POS"} • {player.teamName||"Team"}</Text>{current?<Text style={styles.now}>NOW BATTING</Text>:null}</View>{current?<Ionicons name="caret-back" size={22} color="#f59e0b"/>:null}</View>}
 return <><Stack.Screen options={{headerShown:false}}/><View style={styles.screen}><ScrollView contentContainerStyle={styles.container}><View style={styles.top}><Pressable style={styles.back} onPress={back}><Ionicons name="chevron-back-outline" size={19} color="#fff"/><Text style={styles.backText}>Back to Game</Text></Pressable></View><View style={styles.hero}><Text style={styles.gameTitle}>{String(p.gameTitle||"")}</Text><Text style={styles.mode}>TEAM LINEUP</Text><Text style={styles.live}>🟢 LIVE LINEUP FEED</Text><Text style={styles.updated}>{lastUpdated}</Text></View>{loading?<ActivityIndicator size="large" color="#1f4e9e"/>:<View style={styles.card}><View style={styles.identity}><Image source={squad==="East"?require("../assets/East.png"):require("../assets/West.png")} style={styles.logo} resizeMode="contain"/><Text style={[styles.teamTitle,squad==="East"?styles.east:styles.west]}>{squad.toUpperCase()} ALL-STARS</Text><Text style={styles.manager}>Manager: {manager||"TBD"}</Text></View><View style={[styles.header,squad==="East"?styles.eastBg:styles.westBg]}><Text style={styles.headerText}>{squad.toUpperCase()} BATTING LINEUP ({batting.length})</Text></View>{batting.length?batting.map((x,i)=>row(x,i)):<Text style={styles.empty}>No saved batting lineup yet.</Text>}<View style={[styles.header,styles.subHead,squad==="East"?styles.eastBg:styles.westBg]}><Text style={styles.headerText}>{squad.toUpperCase()} SUBSTITUTES</Text></View>{subs.length?subs.map(x=>row(x)):<Text style={styles.empty}>No substitutes listed.</Text>}</View>}<View style={styles.footer}><Text style={styles.footerText}>NTABL All-Star App • Version 1.0</Text></View></ScrollView></View></>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#eef2f7"},container:{width:"100%",maxWidth:1000,alignSelf:"center",padding:12,paddingTop:18,paddingBottom:70},top:{alignItems:"flex-start",marginBottom:8},back:{backgroundColor:"#1d4ed8",borderRadius:10,paddingVertical:10,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:5},backText:{color:"#fff",fontSize:15,fontWeight:"900"},hero:{alignItems:"center",backgroundColor:"#fff",borderRadius:18,borderWidth:1,borderColor:"#e5e7eb",padding:20,marginBottom:18,shadowColor:"#000",shadowOpacity:.08,shadowRadius:12,shadowOffset:{width:0,height:4},elevation:4},gameTitle:{color:"#111827",fontSize:Platform.OS==="web"?30:24,fontWeight:"900",textAlign:"center"},mode:{color:"#1f4e9e",fontSize:14,fontWeight:"900",letterSpacing:1,marginTop:3},live:{color:"#15803d",fontSize:18,fontWeight:"900",marginTop:9},updated:{color:"#6b7280",fontSize:12,fontWeight:"700",marginTop:2},card:{backgroundColor:"#fff",borderRadius:16,overflow:"hidden",borderWidth:1,borderColor:"#e5e7eb"},identity:{alignItems:"center",padding:18},logo:{width:120,height:110},teamTitle:{fontSize:23,fontWeight:"900"},east:{color:"#d71920"},west:{color:"#174ea6"},manager:{color:"#111827",fontSize:19,fontWeight:"900",marginTop:8},header:{paddingVertical:10,paddingHorizontal:12,alignItems:"center"},eastBg:{backgroundColor:"#d71920"},westBg:{backgroundColor:"#174ea6"},headerText:{color:"#fff",fontSize:15,fontWeight:"900"},subHead:{marginTop:14},row:{minHeight:62,flexDirection:"row",alignItems:"center",paddingVertical:8,paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:"#e5e7eb"},currentRow:{backgroundColor:"#fef3c7",borderLeftWidth:5,borderLeftColor:"#f59e0b"},order:{width:30,color:"#6b7280",fontSize:14,fontWeight:"800"},jersey:{width:65,fontSize:16,fontWeight:"900"},info:{flex:1},name:{color:"#111827",fontSize:16,fontWeight:"900"},meta:{color:"#6b7280",fontSize:12,fontWeight:"700",marginTop:2},now:{color:"#b45309",fontSize:10,fontWeight:"900",marginTop:3},empty:{padding:18,textAlign:"center",color:"#6b7280",fontWeight:"700"},footer:{marginTop:14,alignItems:"center"},footerText:{color:"#6b7280",fontSize:12,fontWeight:"700"}});
